### ISSUE TITLE
Macro Support

### ISSUE THREAD

**Issue by hyperxmason** [Zalafina/QKeyMapper#10]
Hi Zalafina, you have everything I could ever ask for in this software I was wondering if you could add a macro section for recording and playing back macros on a certain key. This is the best program I have ever used for mapping with Interception and ViGEmBus.

**Comment by Zalafina** [comment]
I'm glad you like this program.

Because the previous implementation of the software did not take into account the addition of macro recording functionality, the most feasible way based on the existing functionality and code is to add a key that detects and stores the user's input as a mapped key string. This can save some manual work of writing the mapped key strings.

At this stage, adding the above user input conversion feature does not seem to be a simple task.

Therefore, to ensure that the existing functionality is not affected as much as possible, it is currently impossible to determine how long it will take to add this feature.
