### ISSUE TITLE
Thank you for making this :) ❤️ 

### ISSUE THREAD

**Issue by hyperxmason** [Zalafina/QKeyMapper#7]
Thanks for making this man you need a donation button or something bro this is an awesome program.

**Comment by Zalafina** [comment]
> Thanks for making this man you need a donation button or something bro this is an awesome program.
Thank you for your star. I'm glad that you like this program.
I started developing this program in my spare time because of my own need for a key mapping tool. Therefore, I incorporated some of my personal requirements and habits into it, and I also listened to the feedback from some Chinese users.
Since I am using it myself, I will continue to update and maintain the program even without donations.
